### ISSUE TITLE
Needed Data Science Project (Make sure that Project is  not available in this repo.)

### ISSUE THREAD

**Issue by py3-coder** [py3-coder/Model-EDA-Analysis-CART#2]
Just Comment Below and add your Project Read the guidelines Properly.

**Comment by runtime-error2905** [comment]
Yes @py3-coder  , I want to contribute New data science project.

**Comment by py3-coder** [comment]
Go ahead @runtime-error2905

**Comment by abhijeet49** [comment]
Yes @py3-coder, I want to add my Data Science Projects
